### PR TITLE
Don't assume HTMLElement is in the global scope

### LINKED ISSUE #98: ReferenceError: HTMLElement is not defined
Hello,
I'm using Webstorm to run Mocha tests (on react components) using Chai together with Enzyme, Sinon and Sinon-chai.

I'm doing something like this: 
`expect(ChildSpy).to.have.been.calledWithMatch({a:'a', b: 'b'}); ` that basically is the same as saying:
`sinon.assert.calledWith(ChildSpy, sinon.match({a:'a', b: 'b'}));`.

However I use it I receive and exception from this packages, exactly [from this line](https://github.com/chaijs/type-detect/blob/master/index.js#L159): 

```
ReferenceError: HTMLElement is not defined
    at typeDetect (node_modules/type-detect/index.js:159:24)
    at typeOf (node_modules/sinon/lib/sinon/util/core/typeOf.js:6:12)
    at Object.match (node_modules/sinon/lib/sinon/match.js:103:16)
    at Context.<anonymous> (test/main.js:106:45)
``` 

Apparently the `HTMLElement` used in this function is not defined. 
Does that depend on the node version or maybe was this package conceived to run in the browser and not in node?

```
if (obj instanceof HTMLElement && obj.tagName === 'BLOCKQUOTE') {
    return 'HTMLQuoteElement';
}
```

Maybe there is a check somewhere to understand if we are in a browser or not but I could have make things difficult to check because before starting my tests I do this:

```
// Setup for enzyme: http://airbnb.io/enzyme/docs/guides/jsdom.html
const doc = jsdom.jsdom('<!doctype html><html><body></body></html>', {
  url: 'http://localhost'
});
const win = doc.defaultView;

// Setup for react test-utils 'renderIntoDocument':
// it requires window, window.document and window.document.createElement
// globally available before you can import React
global.document = doc;
global.window = win;
global.navigator = win.navigator;
```

So type-detect believes is in a browser when in fact it's not? 🤔

### PR DESCRIPTION
**Pull request by jetpacmonkey**
Instead uses `globalObject.HTMLElement`, to avoid breaking in a node environment where `HTMLElement` is not defined.

Closes #98

### CODE REVIEW

**Comment by keithamus** [comment]
Thanks for the PR @jetpacmonkey. Could we also get some tests for this? Or some information on how you have come to reproduce the error?

**Comment by meeber** [comment]
@jetpacmonkey Could you provide a bit more detail about the problem you're running into, and the surrounding circumstances?

The lines you changed are currently only run when `isDom` is true. `isDom` is only `true` when `globalObject` contains a `location` and `document` property.  So it sounds like you have an environment that is browser-like, but lacking `HTMLElement`. But if that's the case, then although changing it to `globalObject.HTMLElement` will stop an error from being thrown, since it'll now reference `undefined`, the resulting logic doesn't really make sense, as it translates to `obj instanceof undefined`.

**Comment by jetpacmonkey** [comment]
Hmm, you're right. I'm using jsdom in my test environment, and only put a few values from the `window` object (including `location` and `document`) into the `global` scope. I updated my dependency on Sinon, and suddenly all of my tests that use `Sinon.match` (which depends on this library) started breaking. I'd rather not copy the entirety of my jsdom window into global if I don't have to, since the writers of jsdom call it an [antipattern](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global).

**Comment by keithamus** [comment]
> only put a few values from the `window` object (including `location` and `document`) into the global scope

Do you need this in the global scope, given as you've already said this is an antipattern?

**Comment by jetpacmonkey** [comment]
True, doing less of an antipattern is still an antipattern :)

I'll see if I can remember why I did that, and remove whatever's depending on it. Thanks for the quick responses!

**Comment by keithamus** [comment]
@jetpacmonkey did you get anywhere with that? I think unless there's a super solid usecase for this, I'd rather close the PR. Thoughts?

**Comment by LeonardoGentile** [comment]
I have the exact use case of @jetpacmonkey, I'm using jsdom, and whenever using sinon.match I get this error, see #98

**Comment by LeonardoGentile** [comment]
See also: https://github.com/airbnb/enzyme/issues/888

**Comment by jetpacmonkey** [comment]
I think enzyme might be the real problem here, since it expects to execute in a browser-like environment, and I haven't come across a great tool for sandboxing browser-like environments. Someone should write one of those...

Anyways, it appears that I don't have a great way to get around that antipattern. However, what's really confusing me right now is the fact that I'm not intentionally putting `location` onto the global scope in my test environment, as far as I can see. This is feeling more and more to me like a bad interaction between various testing libs, which would mean this PR probably isn't the best solution. But... I still don't know what the actual solution should be.

**Comment by jetpacmonkey** [comment]
This appears to be relevant: https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md#describewithdom-api-and-clearing-the-document-after-every-test

Antipattern or no, a shared global DOM appears to be required for testing React components.

**Comment by LeonardoGentile** [comment]
@jetpacmonkey I'm also not putting location into the global..

**Resuming**:   
enzyme is suggesting us [to do](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md) something that the jsdom docs tell us [not to do](https://github.com/tmpvar/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global) saying that [there is no better way](https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md#describewithdom-api-and-clearing-the-document-after-every-test) at the moment to do this.

Now, apart from that, who is adding the `location` to the global? Apparently shouldn't be jsdom. 
Mistery..  

My configuration before loading the react tests:  
```
const doc = jsdom.jsdom('<!doctype html><html><body></body></html>', {
  url: 'http://localhost'
});
const win = doc.defaultView;

// Setup for react test-utils 'renderIntoDocument':
// it requires window, window.document and window.document.createElement
// globally available before you can import React
global.document = doc;
global.window = win;
global.navigator = {
  userAgent: 'node.js'
};
```

**Comment by LeonardoGentile** [comment]
@keithamus according to [this comment](https://github.com/airbnb/enzyme/issues/888#issuecomment-294249935) from enzyme member he think this should be an issue of type-detect.

What do you think?

As temp fix until this will be solved I can only see an extra line in my config before running the tests:

```
// [...] continues from above comment
global.HTMLElement = win.HTMLElement;
```

**Comment by jetpacmonkey** [comment]
So, the initial reason for not merging this PR as it was presented was that `obj instanceof undefined` "doesn't make sense". However, it _does_ avoid things unexpectedly breaking, and it doesn't cause any false positives. The only case where it has any effect at all is arguably an antipattern, but it's also a pattern that's explicitly recommended by at least one popular testing library.

Plus, I'd argue that relying on implicit globals any more than is absolutely necessary is an antipattern itself. @keithamus thoughts?

**Comment by meeber** [comment]
at work so cant get into detail, but essentially the pr needs to be updated
so that the tests involving HTMLElement are skipped if its undefined.
checking if it's defined should occur at the top with all the other checks.

**Comment by jetpacmonkey** [comment]
Alright, I can do that.

**Comment by keithamus** [comment]
I had two real concerns initially with the PR; one being I wasn't totally satisfied with _why_ we should make the change, as it seems we have valid enough code. I'm satisfied now, however, that there is clear precedent for us to be more defensive.

My larger concern is that I'd like some tests to prevent regressions in future. However this is a simple enough change and has hung around for nearly a month so I'm willing to forgo the need for tests. I would however agree with @meeber - `isDOM` should probably also check for `'HTMLElement' in globalObject` so skip those checks if we're in a faked out DOM like jsdom. Update this and I'm happy to merge.

**Comment by jetpacmonkey** [comment]
You know, I just re-read what @LeonardoGentile [wrote](https://github.com/chaijs/type-detect/pull/91#issuecomment-294240057). Checking if it's in the `globalObject` won't actually solve anything, because when a Node environment adds `window` to the global scope, `globalObject` isn't actually the global object, it's `global.window`. I really think relying on something to be in global scope instead of explicitly reading it from `globalObject` is a mistake.

**Comment by jetpacmonkey** [comment]
And I have no problem writing a couple of tests for this. I just wanted to make sure that this was a solution that you guys were ok with before I spent the time.

**Comment by meeber** [comment]
Upon further reflection, I think we should do two things here:

1. Improve `type-detect`'s global object detection so that in Node it always uses `global` as the global object, even if `global.window` is defined. According to [this post](http://stackoverflow.com/questions/3277182/how-to-get-the-global-object-in-javascript), a reliable option is: `var globalObject = Function('return this')();`

2. Make it so that browser-related type checks are only performed if ALL browser-related globals being used by `type-detect` are defined. If this is done, then it doesn't matter if `HTMLElement` or `globalObject.HTMLElement` is used for the actual equality comparison, since the equality comparison will only occur in the first place if `HTMLElement` has already been verified to exist.

**Comment by shvaikalesh** [comment]
> `Function('return this')();`

has CSP issues, otherwise 👍

**Comment by jetpacmonkey** [comment]
@meeber I pushed up a check that should do what you described. I suppose for the new tests, I'll just add a jsdom devDependency and re-run the node tests using that?

**Comment by jetpacmonkey** [comment]
The funny thing is, with my original change, it actually _wouldn't_ have been `obj instanceof undefined`, since `globalObject` was the jsdom `window`, so `globalObject.HTMLElement` probably would have been defined.

**Comment by jetpacmonkey** [comment]
Oh, and apparently the linter hated that commit. Looks like it was disabled for that line anyways, before, so I guess I'll do that again.

File: index.js [hunk 1]
```diff
@@ -5,8 +5,31 @@
...
  */
 var promiseExists = typeof Promise === 'function';
-var globalObject = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : self; // eslint-disable-line
-var isDom = 'location' in globalObject && 'document' in globalObject;
+
+/* eslint-disable */
+// See http://stackoverflow.com/a/6930376
+var globalObject;
+try {
+  globalObject = Function('return this')() || (42, eval)('this');
```
Comment (meeber) [inline index.js]: It's my understanding that all that's needed here is `var globalObject = Function('return this')();`. Not the `||` nor the `try/catch`.

File: index.js [hunk 2]
```diff
@@ -5,8 +5,31 @@
...
+/*
+ * All of these attributes must be available on the global object for the current environment
+ * to be considered a DOM environment (browser)
+ */
+var domIndicatorAttributes = [
+  'location',
+  'document',
+  'navigator',
+  'HTMLElement',
+];
```
Comment (meeber) [inline index.js]: One thing I'm concerned about here is that lines like this `if (obj === (globalObject.navigator || {}).mimeTypes) {` indicate that sometimes `globalObject.navigator` isn't expected to be defined, even in a valid browser environment. However, this isn't my area of expertise. @keithamus @shvaikalesh thoughts?

**Comment by meeber** [comment]
@jetpacmonkey Thanks for working on this! Regarding tests: not sure how I feel about pulling in `jsdom` as a dependency. I think it's reasonable to fix this specific problem, but making "all tests must pass in jsdom" an absolute requirement for all future builds is a bit of a leap at this point. I'm not really sure at the moment what I think the best strategy is here. I'm not opposed to moving forward without additional automated tests for this. Thoughts @keithamus @shvaikalesh?

File: index.js (hunk 1 above)
Comment (shvaikalesh) [inline index.js]: On top of what @meeber has mentioned, I would prefer `new Function`. `new` with constructors is the new black in ES6. Also, this won't work in Chrome OS extensions for example. More on CSP: https://github.com/jashkenas/underscore/issues/906.

File: index.js [hunk 3]
```diff
@@ -5,8 +5,31 @@
  * MIT Licensed
  */
 var promiseExists = typeof Promise === 'function';
-var globalObject = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : self; // eslint-disable-line
-var isDom = 'location' in globalObject && 'document' in globalObject;
+
+/* eslint-disable */
```
Comment (shvaikalesh) [inline index.js]: I would prefer to disable specific rule, not the whole eslint.

Comment (jetpacmonkey) [inline index.js]: Sure. I just did it this way because it was originally `// eslint-disable-line`

File: index.js (hunk 1 above)
Comment (jetpacmonkey) [inline index.js]: This was, for the most part, copied from that StackOverflow post. The `try/catch` is needed because of CSP. `window` is a safe fallback because CSP doesn't exist in non-browser environments, afaik. The `||` I wasn't quite as clear on. Something to do with `use strict` if I was reading that SO post correctly?

@shvaikalesh will it "not work" even with the `try/catch`? I thought I was already accounting for CSP... Also, I agree about using `new`.

File: index.js (hunk 2 above)
Comment (shvaikalesh) [inline index.js]: I've never encountered a browser environment without `navigator` defined.

File: index.js [hunk 4]
```diff
@@ -5,8 +5,31 @@
...
+ */
+var domIndicatorAttributes = [
+  'location',
+  'document',
+  'navigator',
+  'HTMLElement',
+];
+var isDom = domIndicatorAttributes.every(function inGlobal(attr) {
+  return attr in globalObject;
+});
```
Comment (keithamus) [inline index.js]: Not massively keen on doing these kind of iterations upfront. Would rather see the 4 `attr in globalObject` lines hardcoded than using an array.

**Comment by keithamus** [comment]
Okay I've modified the PR to fix up all the comments. I'm happy with this but I'll dismiss my PR as I've contributed. @shvaikalesh @meeber could you please check through this and if we're all happy with this we can squash and merge as a `fix:` commit to get it released.

**Comment by shvaikalesh** [comment]
I think we should avoid `new Function` (because of CSP) and do something like `var globalObject = typeof self === 'object' ? self : global`.

**Comment by keithamus** [comment]
Okay @shvaikalesh how about this? Best of both worlds?

**Comment by meeber** [comment]
@shvaikalesh @keithamus Can you talk me through how the global object detection now works?

File: index.js [hunk 5]
```diff
@@ -1,12 +1,29 @@
...
+ * All of these attributes must be available on the global object for the current environment
+ * to be considered a DOM environment (browser)
+ */
+if (typeof window === 'object' &&
+  'document' in window &&
+  'navigator' in window &&
+  'HTMLElement' in window
+) {
+  isDom = true;
+  globalObject = window; // eslint-disable-line no-undef
```
Comment (shvaikalesh) [inline index.js]: I think we can remove this line: if we have `window` object, it is equal to `self`

**Comment by shvaikalesh** [comment]
@meeber 

current code:

```js
var globalObject = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : self;
```

PR:

```js
var globalObject = typeof self === 'object' ? self : global;
```

Kinda the same thing, except that the latter option relies on `self == window`.

**Comment by keithamus** [comment]
Okay, updated. We should be good now right? Whoever merged don't forget to squash+merge as `fix: `

File: index.js [hunk 6]
```diff
@@ -1,12 +1,24 @@
...
 /* !
  * type-detect
  * Copyright(c) 2013 jake luer <jake@alogicalparadox.com>
  * MIT Licensed
  */
 var promiseExists = typeof Promise === 'function';
-var globalObject = typeof window !== 'undefined' ? window : typeof global !== 'undefined' ? global : self; // eslint-disable-line
-var isDom = 'location' in globalObject && 'document' in globalObject;
+
+/* eslint-disable no-undef */
```
Comment (keithamus) [inline index.js]: Oops, forgot to re-enable this one. Can't right now - but will get to it later.

**Comment by mroderick** [comment]
The build failed because of ESLint errors

```text
/home/travis/build/chaijs/type-detect/index.js
   9:47  error  'self' is not defined    no-undef
  16:17  error  'window' is not defined  no-undef
  17:18  error  'window' is not defined  no-undef
  18:20  error  'window' is not defined  no-undef
```

It would be easy to fix this with a few well placed comments:

```js
// eslint-disable-next-line no-undef id-blacklist
var globalObject = typeof self === 'object' ? self : global;
/*
 * All of these attributes must be available on the global object for the current environment
 * to be considered a DOM environment (browser)
 */
/* eslint-disable no-undef */
var isDom = typeof window === 'object' &&
  'document' in window &&
  'navigator' in window &&
  'HTMLElement' in window;
/* eslint-enable no-undef */
```

Who can fix the branch, so we can get this merged?

**Comment by keithamus** [comment]
@meeber @shvaikalesh shall we get this reviewed and merged?

**Comment by keithamus** [comment]
> Is there any plausible scenario in which isDom gets set to true (because window is an object and has the document, navigator, and HTMLElement properties), but globalObject gets set to something other than window on line 11? If so, then the code won't behave as expected.

Perhaps this is a bug, like the one is this PR, which we'll cross when someone experiences it. While technically possible, I doubt we'll ever see it - if someone is trying to emulate the DOM it's probably a mistake to be missing `self`.

**Comment by mroderick** [comment]
Thank you 💯 

It would be great if someone could publish a new release to npm

**Comment by vieiralucas** [comment]
@gpoole I think we can make a release as soon as #112 gets merged

**Comment by gpoole** [comment]
Ah perfect, thanks @vieiralucas!

**Comment by vieiralucas** [comment]
@gpoole [@chaijs/type-detect v4.0.4 j](https://github.com/chaijs/type-detect/releases/tag/v4.0.4)ust got released
