### PR TITLE
fix: favour extended array toStringTag where available

### LINKED ISSUE #49: Extended standard types and Symbol.toStringTag
Might be a question more than a bug, but how would you expect this to react?

```
const type = require('type-detect');
class ExtendedArray extends Array {
  get [Symbol.toStringTag]() {
    return 'ExtendedArray';
  }
}
console.log(type(new ExtendedArray())); //=> 'array'
```

My initial expectation was that I would receive back `ExtendedArray` through the use of `Symbol.toStringTag`, but the code returns `array`, from [here](https://github.com/chaijs/type-detect/blob/f7dcaf02f23a7ad2628fd52efc5510d2fc3cc3b3/index.js#L97-L99). Is this intended?

### PR DESCRIPTION
**Pull request by keithamus**
Closes #49. Supersedes #50 by adding tests. Thanks @dvlsg!

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -92,7 +92,10 @@ module.exports = function typeDetect(obj) {
    * Post:
    *   array literal      x 22,479,650 ops/sec ±0.96% (81 runs sampled)
    */
-  if (Array.isArray(obj)) {
+  if (
+    Array.isArray(obj) &&
+    (symbolToStringTagExists === false || typeof obj[Symbol.toStringTag] === 'undefined')
```
Comment (shvaikalesh) [inline index.js]: !(`Symbol.toStringTag` in obj)

**Comment by lucasfcosta** [comment]
LGTM, good job, Keith!

**Comment by lucasfcosta** [comment]
Oh god, what a shame, I didn't see @shvaikalesh's comment.
Sorry for that 😓 
Let me fix this.
